server:
  port: 9755

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
    host: zuihou.redis.host
    port: 6379

zuihou:
  mysql:
    file:
      database: zuihou_file_dev       # 根据环境更改
    host: zuihou.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: Biyu5YzU+6sxDRbmWEa3B2uUcImzDo0BuXjTlL505+/pTb+/0Oqd3ou1R6J8+9Fy3CYrM18nBDqf6wAaPgUGOg==
  file:
    upload-path-prefix: D:\home\uploadfile\
    remote-uri-prefix: http://192.168.65.147:6080/
    fastdfs:
      enabled: false


 # id生成器机器掩码
id-generator:
  machine-code: 1